version: "3"
services:
  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: rachel
      MYSQL_PASSWORD: rachel
      MYSQL_ROOT_PASSWORD: rachel

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
