spring:
#  profiles:
#    active: dev
#  application:
#    name: portfolioServer

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: portfolio
  session:
    jdbc:
      initialize-schema: always
    timeout: 900
  main:
    web-application-type: servlet
server:
  port: 8080
