spring:
#  profiles:
#    active: dev
#  application:
#    name: portfolioServer

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: password


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: portfolio
  session:
    jdbc:
      initialize-schema: always
    timeout: 900
  main:
    web-application-type: servlet
server:
  port: 8080
